#!/bin/bash
# Run and link the shard cluster
# parameters:
# run-shard-cluster.sh CLUSTER-NAME NUM-SHARD-SERVERS NUM-SHARD-PER-SERVER

# Parameters
CLUSTER=$1
SVS=$2
SH_PER_SV=$3

# Docker Repo login
REPO="docker-repo:2061"
RUSER='prioridata'
RPASS='WeL0veData'
EMAIL='fred@prioridata.com'

BEGIN_SHARD_PORT=28000
let "END_SHARD_PORT = $BEGIN_SHARD_PORT + $SH_PER_SV - 1"
ZONE="us-central1-a"
BOOTDISKTYPE="pd-ssd"
SDEV=(none /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/sdg /dev/sdh)
LSSDSIZE=373

function launch_docker { # (name, image)
    name=$1
    image=$2
    other=$3
    #docker run --name=$name -d --hostname=$name --link=pdns.srv:pdns.srv  --dns=$PDNS $other $image && register $name
}

# Launch a Google Docker Server Instance
function launch_sv { # name machinetype localssds
    name=$1
    machinetype=$2
    localssds=$3
    
    lsd=''
    for i in $(seq $localssds); do
        lsd="$lsd --local-ssd interface=SCSI "
    done
    
    echo "Creating $name as $machinetype with $localssds local SSDs"
    gcloud compute instances create $name \
        --image template-docker-centos7-image \
        --description="generated by run-shard-cluster.sh" \
        --zone=$ZONE \
        --boot-disk-type=$BOOTDISKTYPE \
        --machine-type=$machinetype \
        $lsd

    sleep 30
    echo "Base configuration of $name"
    gcutil ssh $name <<EOF
sudo su -
echo never > /sys/kernel/mm/transparent_hugepage/enabled
lvmetad
EOF

    lvmcanidates=''
    for i in $(seq $localssds); do
        gcutil ssh $name <<EOF
sudo pvcreate ${SDEV[i]}
EOF
        lvmcanidates="$lvmcanidates ${SDEV[i]}"
    done

    if (($localssds > 0)); then
        let "ssize = $LSSDSIZE * $localssds"
        gcutil ssh $name <<EOF
sudo su -
vgcreate ssdvol $lvmcanidates
lvcreate --wipesignatures y -n data ssdvol -l 95%VG
lvcreate --wipesignatures y -n metadata ssdvol -l 5%VG
service docker start && docker login --email=$EMAIL --password=$RPASS --username=$RUSER https://$REPO
EOF
    fi
}

function launch_cfg { # (name, image)
    name=$1
    image=$2
    other=$3
    echo "launch_cfg($name, $image)"
    launch_sv $name n1-standard-1 1
    gcutil ssh $name <<EOF
sudo su -
docker pull $REPO/$image
docker run --name=$name -d --net='host' --publish=27019:27019 $REPO/$image 
EOF
}

function launch_shs { # (name, image)
    name=$1
    image=$2
    other=$3
    echo "launch_shs($name, $image)"
    launch_sv $name n1-highmem-4 2
    gcutil ssh $name <<EOF
sudo su -
docker pull $REPO/$image
EOF

for port in $(seq $BEGIN_SHARD_PORT $END_SHARD_PORT);  do
    echo "SHARD ${name}:${port}"
    gcutil ssh $name "sudo docker run --name=${name}-${port} -d --publish=$port:27017 $REPO/$image"
done
}

echo "Creating and running for cluster $CLUSTER: shards servers: $SVS, shards per server: $SH_PER_SV"

###############################################################
# NOTE WELL
# Firstly, TokuMX requires that transparent hugepages disabled.
# for dockers, this must be done on the HOST system.
sudo echo never > /sys/kernel/mm/transparent_hugepage/enabled

# Start the all-important DNS server for this host's cluster.
# TODO: Use the Ambassador pattern to tie together a cluster across
# multiple boxen.
#docker run --name=pdns.srv -d --hostname=pdns.srv pdns
#getip pdns.srv
#PDNS=$ip
#sleep 30

# Register the name server with itself (later we'll use this)
#register pdns.srv
#echo "PDNS Server is on $PDNS"

# Config servers
for i in $(seq 0 2); do
    launch_cfg ${CLUSTER}-cfg$i tokumx/toks-config &
done


# Actual shards (should be repl clusters, but for now...)
for i in $(seq 0 $(($SVS - 1)) ); do
    launch_shs ${CLUSTER}-shs$i tokumx/toks-rep &
done

# MongoS gateway. Access point to the shards.
#launch mongos.srv tokumx/toks-s --publish=27017:27017

#TODO: setup the shards via a mongo client
